%/ Load Moisture Tracking Parameters
function [str_RHc_dqc, str_remark, str_src_z, str_years, WSV_lon, WSV_lat,...
          maxtraj_day, str_BLH_factor, str_optimal, str_traj_rm_jump, dt_slct, data_folder,...
          plotting_folder, WSV_dir, str_expmntinfo, basin_catalog, str_domain, str_domain_trajfile, str_sharpcut, forcing, stdate, eddate]...
            = load_tracking_param(varargin)

    pnames = {'expmnt', 'ldirect', 'output_res', 'dt', 'year_list', 'optimal_rr', 'RHc_dqc_scheme', 'from_basin', 'masterfolder'};  
    dflts  = cell(1, length(pnames));
    [          expmnt,   ldirect,   output_res,   dt,   year_list,   optimal_rr,   RHc_dqc_scheme,   from_basin,   masterfolder] = internal.stats.parseArgs(pnames, dflts, varargin{:}); %/ parse function arguments
    
    %%
    %===============================================================================
    %/      Author: Franklin Cheng (fandycheng@ust.hk)
    %/ Last Update: 29 Jan 2024
    %/
    %/ Description: This function is designd to load the moisture tracking information
    %/              output by the program (moisture_tracking.m).
    %===============================================================================

    %/ Derive forwad trajectories from domain-fill and the uptake map
    fprintf('*** NOTE: For deriving trajs, WaterSip and WaterDrip variables, run ''moisture_tracking.m''. ***\n')
    fprintf('*** NOTE: Make sure ''masterfolder'' is the same as that in ''moisture_tracking.m''. ***\n')

    %/ Specify the forcing data to FLEXPART
    if contains(expmnt, '_EA_')
        forcing = 'EA';
    elseif contains(expmnt, '_CERA_')
        forcing = 'CERA';
    else
        error('What forcing was to drive the experiment %s?', expmnt);
    end

    %>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
    %/ Loading tracking information (generated by moisture_tracking.m)

    tracking_info_filename = sprintf('tracking_info_%s_%s_%.2f_%d_%d-%d_%.2f_%d_%d.mat',...
                                expmnt, ldirect, output_res, dt, year_list(1),year_list(end),optimal_rr,from_basin,RHc_dqc_scheme);

    data_folder = strcat(masterfolder, expmnt, '/prcssd_data_4plotting/');
    tracking_info_fullpath = fullfile(data_folder, tracking_info_filename);
    if isfile(tracking_info_fullpath)
        load(tracking_info_fullpath, 'S');
        fprintf('!!! Tracking info is loaded: %s !!!', tracking_info_fullpath);
    else
        error('Tracking info is not found: %s! Please run moisture_tracking.m to generate it!', tracking_info_fullpath)
    end

    [~, ~, ~, ~, str_RHc_dqc] = read_RHc_dqc_scheme(RHc_dqc_scheme, forcing);
    % [basin_catalog, str_domain_trajfile, str_domain] = load_from_basin('from_basin', from_basin);
    
    stdate              = S.stdate;
    eddate              = S.eddate;
    maxtraj_day         = S.maxtraj_day;
    str_optimal         = S.str_optimal;
    str_remark          = S.str_remark;
    str_traj_rm_jump    = S.str_traj_rm_jump;
    str_BLH_factor      = S.str_BLH_factor;
    str_src_z           = S.str_src_z;
    dt_slct             = S.dt_slct;
    str_expmntinfo      = S.str_expmntinfo;
    plotting_folder     = S.plotting_folder;
    WSV_dir             = S.WSV_dir;
    str_sharpcut        = S.str_sharpcut;
    basin_catalog       = S.basin_catalog;
    str_domain_trajfile = S.str_domain_trajfile;
    str_domain          = S.str_domain;

    mkdir(char(plotting_folder));
    str_years = sprintf('_%d-%d', year_list(1), year_list(end));
    WSV_lon = 0:output_res:360-output_res;                    %/ this is the lon that I input to calcuate uptake map, although in FLexpart it is in [-179, 180].
    WSV_lat = -90:output_res:90;
    fprintf('======================================================================\n');
    fprintf('=== NOTE: RHc_dqc_scheme = %02d, from_basin = %02d. Period: %d-%d. ===\n', RHc_dqc_scheme, from_basin, year_list(1), year_list(end))
    fprintf('======================================================================\n');
end